### ISSUE TITLE
Container Append Problem

### ISSUE THREAD

**Issue by rmclaren** [rmclaren/bufr-query#13] opened 2024-07-12 20:15 UTC
When I appended one container to the other for amsua which has two input files, I got an error due to different dimension paths (see details below). 
I am not sure if this is caused by the different query for lat and lon in the mapping files:

one file has:
```
 latitude:
      query: '*/CLATH'
    longitude:
      query: '*/CLONH'
```

and the other has:
```
    latitude:
      query: '*/CLAT'
    longitude:
      query: '*/CLON'
```

Any suggestions?

Thanks,

Xin

--------------------------- error messages -----------

```
Exception: Bad parameter: Cannot append data with different dimension paths.
OOPS_TRACE[0] RoundRobin destructed
OOPS_TRACE[0] NonoverlappingDistribution destructed
OOPS_TRACE[0] Distribtion destructed
Exception:      Reason: Python error: RuntimeError: Bad parameter: Cannot append data with different dimension paths.

At:
  bufr2ioda_amsua.py(52): create_obs_group

        source_column:  0
        source_filename:        /work/noaa/da/eliu/JEDI-ioda/ioda-bundle/ioda/src/engines/ioda/src/ioda/Engines/Script/Script.cpp
        source_function:        ioda::ObsGroup ioda::Engines::Script::openFile(const ioda::Engines::Script::Script_Parameters &, const ioda::Engines::ReaderCreationParameters &, ioda::Group)
        source_line:    319
        stacktrace:
 0# util::stacktrace_current[abi:cxx11]() in /work/noaa/da/eliu/JEDI-ioda/ioda-bundle/build/bin/../lib64/liboops.so
 1# ioda::Exception::add_call_stack() in /work/noaa/da/eliu/JEDI-ioda/ioda-bundle/build/bin/../lib64/libioda_engines.so
 2# ioda::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ioda::detail::compat::source_location::source_location const&, ioda::Options const&) in /work/noaa/da/eliu/JEDI-ioda/ioda-bundle/build/bin/../lib64/libioda_engines.so
```

**Comment by rmclaren** [comment] 2024-07-12 20:25
Are you sure its due to the latitude / longitude fields as those fields have the same dimension paths (`*`)?

**Comment by rmclaren** [comment] 2024-07-12 20:27
Are you trying to merge containers that were read using different mapping files?

**Comment by xincjin-NOAA** [comment] 2024-07-12 21:25
> Are you trying to merge containers that were read using different mapping files?

yes

**Comment by xincjin-NOAA** [comment] 2024-07-12 21:26
> Are you sure its due to the latitude / longitude fields as those fields have the same dimension paths (`*`)?

Actually, I am not sure about this.

**Comment by emilyhcliu** [comment] 2024-07-15 18:32
@rmclaren  -- good news!!!  @xincjin-NOAA and I found the source of error.

The error message from @xincjin-NOAA above is caused by the following check in the bufr-query DataObject.h:

https://github.com/NOAA-EMC/bufr-query/blob/e0d1cb5ba4134517f140e272d4c11af262a2381d/core/include/bufr/DataObject.h#L442-L450

https://github.com/NOAA-EMC/bufr-query/blob/e0d1cb5ba4134517f140e272d4c11af262a2381d/core/include/bufr/DataObject.h#L735-L743

@xincjin-NOAA commented out the lines in the code snippet above, and then the append of containers worked!!  

These two containers have the same channel dimension values (15), but are stored in different path names:
```
  dimensions:
  - name: Channel
    path: '*/BRITCSTC'
    source: variables/sensorChannelNumber
```
```
  dimensions:
  - name: Channel
    path: '*/ATNCHV'
    source: variables/sensorChannelNumber
```
The bufr-query code checks if the containers to be merged have the same path name.  
But the dimension values are the same.  Two containers should be merged without a problem.  
We are wondering if the bufr query code can check the dimension by values, not by names.
In this case, the dimension information is stored in different names.

**Comment by rmclaren** [comment] 2024-07-15 18:55
OK, Ill look at it. The purpose of the append function was originaly to merge 2 identical DataContainers (same in every way)... We might want to make a "merge" tool which lets you combine two disimulat DataContainers in a controlled way.

**Closed as completed** 2024-07-18 14:48 UTC
